name: Cluster Setup
description: Cluster setup for canary test

runs:
  using: "composite"
  steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true

    - name: setup golang
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"

    - name: Install cri-dockerd
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: |
        curl -LO https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.21/cri-dockerd_0.3.21.3-0.ubuntu-focal_amd64.deb
        sudo dpkg -i cri-dockerd_0.3.21.3-0.ubuntu-focal_amd64.deb
        rm -f cri-dockerd_0.3.21.3-0.ubuntu-focal_amd64.deb

    - name: Setup Minikube
      uses: medyagh/setup-minikube@latest
      with:
        minikube-version: "1.34.0"
        kubernetes-version: v1.31.0
        driver: none
        container-runtime: docker
        memory: 6g
        cpus: 2
        addons: ingress
        cni: calico

    - name: install deps
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh install_deps

    - name: print k8s cluster status
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh print_k8s_cluster_status

    - name: build rook
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh build_rook
