name: Cluster Setup
description: Cluster setup for integration test
inputs:
  kubernetes-version:
    description: kubernetes version to use for the workflow
    required: true

runs:
  using: "composite"
  steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true

    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: "1.21"

    - name: Install cri-dockerd
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: |
        curl -LO https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.21/cri-dockerd_0.3.21.3-0.ubuntu-focal_amd64.deb
        sudo dpkg -i cri-dockerd_0.3.21.3-0.ubuntu-focal_amd64.deb
        rm -f cri-dockerd_0.3.21.3-0.ubuntu-focal_amd64.deb

    - name: Setup Minikube
      uses: medyagh/setup-minikube@latest
      with:
        minikube-version: "1.32.0"
        kubernetes-version: ${{ inputs.kubernetes-version }}
        driver: none
        container-runtime: docker
        memory: 6g
        cpus: 2
        addons: ingress
        cni: calico

    - name: print k8s cluster status
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh print_k8s_cluster_status

    # This step is required for all the integration tests except the canary tests
    - name: use local disk
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh use_local_disk_for_integration_test

    - name: build rook
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh build_rook
